package agents;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Painel_prob.java
 *
 * Created on 2/Dez/2009, 15:50:34
 */

/**
 *
 * @author pedro
 */
public class Painel_prob extends javax.swing.JPanel {

    /** Creates new form Painel_prob */
    public Painel_prob(String type, String description , int del) {
        initComponents(type,description, del);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents(String typ,String description , int del) {

        voo = new javax.swing.JLabel();
        desc = new javax.swing.JLabel();
        crew_memb = new javax.swing.JLabel();
        type = new javax.swing.JLabel();
        delay = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(15, 165, 45)));
        setPreferredSize(new java.awt.Dimension(911, 300));

        voo.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.shadow"));
        voo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        voo.setText("");
        voo.setBorder(new javax.swing.border.MatteBorder(null));

        desc.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.shadow"));
        desc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        desc.setText(description);
        desc.setBorder(new javax.swing.border.MatteBorder(null));

        crew_memb.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.shadow"));
        crew_memb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        crew_memb.setText("");
        crew_memb.setBorder(new javax.swing.border.MatteBorder(null));

        type.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.shadow"));
        type.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        type.setText(typ);
        type.setBorder(new javax.swing.border.MatteBorder(null));

        delay.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.shadow"));
        delay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        delay.setText(Integer.toString(del));
        delay.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(voo, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(crew_memb, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(desc, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(delay, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crew_memb, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(desc, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delay, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(voo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
    }// </editor-fold>


    // Variables declaration - do not modify
    private javax.swing.JLabel crew_memb;
    private javax.swing.JLabel delay;
    private javax.swing.JLabel desc;
    private javax.swing.JLabel type;
    private javax.swing.JLabel voo;
    // End of variables declaration

}
